server:
  port: 8085

spring:
  rabbitmq:
    host: 192.168.99.102
    port: 5672
    username: guest
    password: guest

spring.cloud.stream.bindings.output.destination: exchange
spring.cloud.stream.default.contentType: application/json